version: "3.8"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: "0"
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - gpe

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "0"
    restart: unless-stopped
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - prometheus
    networks:
      - gpe

networks:
  gpe:
    driver: bridge
